### ISSUE TITLE
这个项目是不是少了很多资料？比如云端的配置代码有没有提供？

### ISSUE THREAD

**Issue by Jinge666666** [hidewnd/MaterialSystem#1]

**Comment by hidewnd** [comment]
云端配置文件请参考各服务模块resource/application.yml文件
具体配置请查阅 [spring cloud Alibaba Nacos](https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html) 开发文档

**Comment by Jinge666666** [comment]
谢谢，还有那个nginx的配置文件呢？就是反向代理这些配置没找到 可以发一份给我吗，谢谢😊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月14日(周四) 晚上10:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hidewnd/MaterialSystem] 这个项目是不是少了很多资料？比如云端的配置代码有没有提供？ (Issue #1)




 
云端配置文件请参考各服务模块resource/application.yml文件
 具体配置请查阅 spring cloud Alibaba Nacos 开发文档

**Comment by hidewnd** [comment]
请参照项目实际部署方式及nginx的官方文档自行打包并部署前端项目
参考文档：Nginx 配置详解 | 菜鸟教程 (runoob.com)
注1：此毕设论文信息及其他相关材料仅供参考，禁止挪用，后果自负。
注2：项目运行请依据运行环境合理配置启动参数，例如Xms、Xmx、XX:MaxMetaspaceSize




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hidewnd/MaterialSystem"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月15日(星期五) 凌晨1:18
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [hidewnd/MaterialSystem] 这个项目是不是少了很多资料？比如云端的配置代码有没有提供？ (Issue #1)





 谢谢，还有那个nginx的配置文件呢？就是反向代理这些配置没找到 可以发一份给我吗，谢谢😊 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年3月14日(周四) 晚上10:54 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [hidewnd/MaterialSystem] 这个项目是不是少了很多资料？比如云端的配置代码有没有提供？ (Issue #1) 
 
 
 
 
   
 云端配置文件请参考各服务模块resource/application.yml文件 
  具体配置请查阅 spring cloud Alibaba Nacos 开发文档

**Comment by Jinge666666** [comment]
大佬，我想问问这个物料管理项目的nginx，你可以把nginx.conf这个文件给我吗？难道这么大的项目你没用反向代理呀，大佬，可以给我一份nginx的配置吗？，先谢谢您了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月15日(周五) 上午8:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hidewnd/MaterialSystem] 这个项目是不是少了很多资料？比如云端的配置代码有没有提供？ (Issue #1)




 请参照项目实际部署方式及nginx的官方文档自行打包并部署前端项目 
 参考文档：Nginx 配置详解 | 菜鸟教程 (runoob.com) 
 注1：此毕设论文信息及其他相关材料仅供参考，禁止挪用，后果自负。 
 注2：项目运行请依据运行环境合理配置启动参数，例如Xms、Xmx、XX:MaxMetaspaceSize 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "hidewnd/MaterialSystem"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年3月15日(星期五) 凌晨1:18 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [hidewnd/MaterialSystem] 这个项目是不是少了很多资料？比如云端的配置代码有没有提供？ (Issue #1) 
 
 
 
 
 
  谢谢，还有那个nginx的配置文件呢？就是反向代理这些配置没找到 可以发一份给我吗，谢谢😊  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2024年3月14日(周四) 晚上10:54  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.******@***.***&amp;amp;gt;;  
  主题: Re: [hidewnd/MaterialSystem] 这个项目是不是少了很多资料？比如云端的配置代码有没有提供？ (Issue #1)  
   
   
   
   
     
  云端配置文件请参考各服务模块resource/application.yml文件  
   具体配置请查阅 spring cloud Alibaba Nacos 开发文档
